---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[remote_or_s3_file::default]
      - recipe[remote_or_s3_file_test::default]
    attributes:
      aws:
        aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
        region: us-east-1
