# Use Travis's container based infrastructure
sudo: false

language: ruby
# Travis: Bundler that comes with Ruby 2.1.0 is too old (1.6.9)
before_install: gem update bundler
bundler_args: --without kitchen_vagrant
rvm:
- 2.1.0
script:
- bundle exec rake travis
